# 나이브 베이즈 실습
- 독립변수가 범주형 변수인 경우
--> 다항분포 나이브 베이즈 ( Multinomail Naive Bayes )

In [1]:
## Multinomial Naive Bayes 라이브러리
from sklearn.naive_bayes import MultinomialNB
## 난수 생성
import numpy as np 

In [2]:
# 0부터 3까지 난수 생성, 변수 10개, 샘플 사이즈 4개
mNB_train_X = np.random.randint(4,size=(4,10))
mNB_train_y = np.array([1,2,3,4])


In [3]:
mNB_train_X

array([[0, 2, 2, 2, 1, 1, 2, 0, 0, 2],
       [0, 3, 2, 0, 2, 2, 1, 2, 3, 2],
       [1, 0, 0, 2, 3, 3, 2, 2, 1, 0],
       [3, 1, 3, 3, 3, 1, 1, 0, 1, 2]])

In [4]:
mNB_train_y

array([1, 2, 3, 4])

In [6]:
# 학습
mNB = MultinomialNB()
fitted_mNB = mNB.fit(mNB_train_X, mNB_train_y)
# 첫 번째 값의 예측 결과(클래스) 확인
print(fitted_mNB.predict(mNB_train_X[:1]))
# 첫 번째 값의 각 클래스별 확률 확인
fitted_mNB.predict_proba(mNB_train_X[:1])

[1]


array([[0.91914482, 0.01554984, 0.00177523, 0.06353012]])

In [7]:
clmNB_2 = MultinomialNB(class_prior = [0.1,0.5,0.1,0.1])
clmNB_2.fit(mNB_train_X,mNB_train_y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1])

In [8]:
clmNB_2.predict_proba(mNB_train_X[:1]) 

array([[0.86532233, 0.07319643, 0.00167127, 0.05980997]])